### PR TITLE
feat: add `useNonce` composable

### PR DESCRIPTION
**Pull request by trijpstra-fourlights**
_If_ there is still a need for the `useNonce` composable, then this would be the current best solution.

- using the global route middleware makes sure there are no hydration mismatches in SSR
- only when in SPA mode will a cookie be set and read as there is no ssrContext there

### CODE REVIEW

**Comment by vejja** [comment]
No, even in SPA we don't need a cookie
I think I understand where you come from now. You are trying to force the server to regenerate the headers, aren't you ?

**Comment by trijpstra-fourlights** [comment]
> No, even in SPA we don't need a cookie I think I understand where you come from now. You are trying to force the server to regenerate the headers, aren't you ?

No, this is purely about supporting the `useNonce` composable, i.e. read access to the `nonce` value in the browser.

I'm unable to get the nonce value in SPA mode without resorting to a cookie. I suspect this has to do with Nuxt not doing hydration in SPA mode. 

If you think it's possible to access it without cookies, can you show me how?

**Comment by vejja** [comment]
> > No, even in SPA we don't need a cookie I think I understand where you come from now. You are trying to force the server to regenerate the headers, aren't you ?
> 
> No, this is purely about supporting the `useNonce` composable, i.e. read access to the `nonce` value in the browser.
> 
> I'm unable to get the nonce value in SPA mode without resorting to a cookie. I suspect this has to do with Nuxt not doing hydration in SPA mode.
> 
> If you think it's possible to access it without cookies, can you show me how?

The bottom line is that it does not make sense, because an SPA is an html shell which is only loaded once.
Whenever you navigate to another route after the first load, it all happens client-side. You will not hit the server again.
So in that case, it is useless to define a per-route CSP. 
Whatever CSP policy was set on the initial load will be the policy for the entire app.
If you define a different CSP policy for another route, it will not be respected, because you won't hit the server and so the new CSP header will not be received by the client.

Please note that it is exactly the same for SSR. Whatever CSP headers are transmitted by the server on the first load, will be the CSP policy for any subsequent navigation - unless you hit "reload"

In a nutshell, defining CSP policies 'per-route' is, in most cases, useless. 
There is only one CSP policy, which is the one of the initial route, and it should be considered as "app-wise".
At the end of the day, this is how Nuxt apps work by design.

**Comment by trijpstra-fourlights** [comment]
I'm not sure why you're talking about per route CSP, that has nothing to do with it. Perhaps you are a bit confused by the `addRouteMiddleware` in this PR. That's a technique to prevent hydration mismatches in SSR mode. Again, that has nothing to do with the CSP, nor the generation of it.

But thanks for your unnecessarily pedantic comment about how CSP and nonce works. I'm amazed at how I ever got something done before that.

Maybe you could finally show some code as to how the `useNonce` composable should work in SPA mode?

**Comment by vejja** [comment]
Sorry, I know I can sound pedantic... but this is absolutely not what I want to convey
the `useNonce` composable should read :
```
import { useNuxtApp } from '#imports'

export function useNonce () {
  return useNuxtApp().ssrContext?.event?.context.nonce
} 
```
No cookie shall be set or read.

Can you try to explain *why* you need a `useNonce` composable that gives read-access to a cookie in SPA mode?
I'm open to discussion

**Comment by trijpstra-fourlights** [comment]
Unfortunately, that won't work on SPA due to ssrContext being expliclty made empty, see https://github.com/nuxt/nuxt/blob/785b7a3f6ecea9e37d2385f996d4ffcced217fbc/packages/nuxt/src/core/runtime/nitro/renderer.ts#L148

Furthermore, 

```
export function useNonce () {
  return useNuxtApp().ssrContext?.event?.context.nonce
} 
```

will result in hydration mismatches as the client render will essentially have the same problem as the SPA: ssrContext is empty. This can be circumvented (but only in SSR mode) with the global route middleware: that runs on the server, and sets the state using `useState`. Anything saved in `useState` will be hydrated again on the client, so if we then let the `useNonce` composable retrieve that value we don't have a mismatch anymore.

I don't see any way around this unfortunately. It seems that cookies or actively injecting the variable into the response are the only two options in which the server generated nonce value can be known to the client in SPA mode.

Or not supporting SPA mode, but IMO that should be up to the developer, not the module.

**Comment by trijpstra-fourlights** [comment]
> Can you try to explain why you need a useNonce composable that gives read-access to a cookie in SPA mode?
> I'm open to discussion

Sure, imagine a SaaS product where client-specific assets are only known at runtime, because they are, for example, the result of the associated supplier for a specific user. This is only known at runtime, after the user has logged in. 

The associated supplier wants to inject their own tracking scripts and/or branding. Due to this information being only available at runtime, `useHead` cannot be used.

Thus the only way of injecting these resources is by doing a `document.createElement` which requires us to provide the correct nonce in a strict CSP setting.

Without `useNonce` being available in the client (both SSR & SPA), this is impossible. The alternative is to not use a strict CSP, but as I previously argued, this is less secure that exposing the nonce in a cookie.

As far as I know, the cookie cannot be read by an untrusted script, due to the strict CSP.

**Comment by trijpstra-fourlights** [comment]
Sure, whatever mate. Good luck with it all.

**Pull request closed without merging**
